version: '3.8'

services:
  app:
    container_name: texting-duncan
    image: texting-duncan:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always

# TODO:
# setup nginx 